# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- build
- django
- react
- test
variables:
  PYTHON_VERSION: 3.11.5
  MYSQL_DATABASE: "$MYSQL_DB"
  MYSQL_ROOT_PASSWORD: "$MYSQL_PASS"
  MYSQL_USER: "$MYSQL_USER"
  MYSQL_PASSWORD: "$MYSQL_PASS"
django-build-job:
  image: python:latest
  stage: build
  before_script:
  - python -m venv venv
  - source venv/bin/activate
  - cd neuro_arcade
  - pip install -r requirements.txt
  - cd ..
  script:
  - python neuro_arcade/manage.py makemigrations --check
  - python neuro_arcade/manage.py migrate
  - python neuro_arcade/manage.py check
  - python neuro_arcade/populate.py
unit-test-job:
  image: python:latest
  before_script:
  - python -m venv venv
  - source venv/bin/activate
  - cd neuro_arcade
  - pip install -r requirements.txt
  - cd ..
  stage: django
  script:
  - cd neuro_arcade
  - python manage.py test
unit-test-r-job:
  stage: react
  image: node:latest
  before_script:
  - cd neuro_arcade
  - cd reactapp
  - npm install --force
  script:
  - export CI=1
  - npm test
  - npm test -- --coverage
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
