stages:          # List of stages for jobs, and their order of execution
  - build
  - django
  - react

variables:
  PYTHON_VERSION: "3.11.5"
  MYSQL_DATABASE: $MYSQL_DB
  MYSQL_ROOT_PASSWORD: $MYSQL_PASS
  MYSQL_USER: $MYSQL_USER
  MYSQL_PASSWORD: $MYSQL_PASS

django-build-job:
  image: python:latest
  stage: build
  before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  script:
    - python neuro_arcade/manage.py makemigrations --check
    - python neuro_arcade/manage.py migrate
    - python neuro_arcade/manage.py check

unit-test-job: 
  image: python:latest
  before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  stage: django
  script:
    - cd neuro_arcade
    - python manage.py test

unit-test-r-job:
  stage: react
  image: node:latest
  before_script:
    - cd neuro_arcade
    - cd reactapp
    - npm install --force
  script:
    - export CI=1
    - npm test
    #  Maybe try and export as artifact at some point?
    - npm test -- --coverage
