
stages:          # List of stages for jobs, and their order of execution
  - build
  - serverFix
  - django
  - reactCreation
  - react

variables:
  PYTHON_VERSION: "3.11.5"
  MYSQL_DATABASE: $MYSQL_DB
  MYSQL_ROOT_PASSWORD: $MYSQL_PASS
  MYSQL_USER: $MYSQL_USER
  MYSQL_PASSWORD: $MYSQL_PASS

build-job:
  image: python:latest
  stage: build
  before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."


server-job:
  image: python:latest
  before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  stage: serverFix
  script:
    - python neuro_arcade/manage.py makemigrations
    - python neuro_arcade/manage.py migrate
    - python neuro_arcade/manage.py check


unit-test-job: 
  image: python:latest
  before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  stage: django
  script:
    - python neuro_arcade/manage.py test
    - echo "Django Unit Tests Ran"
  only:
    - branches
  except:
    - main


lint-test-job: 
  image: python:3.11
  before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  stage: django
  script:
  - cd neuro_arcade
  - ruff check

format-test-job:
  image: python:3.11
  before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  stage: django
  script:
  - cd neuro_arcade
  - ruff format --check


react-creation:
  stage: reactCreation
  image: node:latest
  before_script:
    - cd neuro_arcade
    - cd reactapp
    - npm install --force
  script:
    echo "React compiled"


unit-test-r-job:
  stage: react
  image: node:latest
  #Temporary until we have tests as it will fail if there are no tests
  allow_failure: true
  before_script:
    - cd neuro_arcade
    - cd reactapp
    - npm install --force
  script:
    - export CI=1
    - npm test --passwithnotests
#  Maybe try and export as artifact at some point?
    - jest --collect-coverage


lint-test-r-job:
  stage: react
  image: node:latest
  before_script:
    - cd neuro_arcade
    - cd reactapp
    - npm install --force
  script:
    - npm run testLint

format-test-r-job:
  stage: react
  image: node:latest
  before_script:
    - cd neuro_arcade
    - cd reactapp
    - npm install --force
  script:
    - npm run testFormat






