image: python:latest

stages:          # List of stages for jobs, and their order of execution
  - build
  - serverFix
  - django
  - react

variables:
  PYTHON_VERSION: "3.11.5"
  MYSQL_DATABASE: $MYSQL_DB
  MYSQL_ROOT_PASSWORD: $MYSQL_PASS
  MYSQL_USER: $MYSQL_USER
  MYSQL_PASSWORD: $MYSQL_PASS

before_script:
  # - apt-get install -y python 3.11.5
  # - update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11.5
  - python -m venv venv
  - source venv/bin/activate
  - ls
  - pip install -r requirements.txt


build-job:       # This job runs in the build stage, which runs first. It sets up the virtual environment in order to run the tests
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

server-job:
  stage: serverFix
  script:
    - python neuro_arcade/manage.py makemigrations
    - python neuro_arcade/manage.py migrate
    - python neuro_arcade/manage.py check


unit-test-job:   # This job runs in the test stage.
  stage: django    # It only starts when the job in the build stage completes successfully.
  script:
    - python neuro_arcade/manage.py test
    - echo "Django Unit Tests Ran"
  only:
    - branches
  except:
    - main

lint-test-job:   # This job also runs in the test stage.
  stage: django    # It can run at the same time as unit-test-job (in parallel).
  script:
    - echo "Linting code... This will take about 10 seconds."
    - sleep 10
    - echo "No lint issues found."

