
stages:          # List of stages for jobs, and their order of execution
  - build
  - serverFix
  - django
  - reactCreation
  - react

variables:
  PYTHON_VERSION: "3.11.5"
  MYSQL_DATABASE: $MYSQL_DB
  MYSQL_ROOT_PASSWORD: $MYSQL_PASS
  MYSQL_USER: $MYSQL_USER
  MYSQL_PASSWORD: $MYSQL_PASS




build-job:
  image: python:latest       # This job runs in the build stage, which runs first. It sets up the virtual environment in order to run the tests
  stage: build
  before_script:
  # - apt-get install -y python 3.11.5
  # - update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11.5
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

server-job:
  image: python:latest       # This job runs in the build stage, which runs first. It sets up the virtual environment in order to run the tests
  before_script:
  # - apt-get install -y python 3.11.5
  # - update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11.5
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  stage: serverFix
  script:
    - python neuro_arcade/manage.py makemigrations
    - python neuro_arcade/manage.py migrate
    - python neuro_arcade/manage.py check


unit-test-job: 
  image: python:latest       # This job runs in the build stage, which runs first. It sets up the virtual environment in order to run the tests
  before_script:
  # - apt-get install -y python 3.11.5
  # - update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11.5
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  stage: django
  script:
    - python neuro_arcade/manage.py test
    - echo "Django Unit Tests Ran"
  only:
    - branches
  except:
    - main

lint-test-job: 
  image: python:3.11       # This job runs in the build stage, which runs first. It sets up the virtual environment in order to run the tests
  before_script:
  # - apt-get install -y python 3.11.5
  # - update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11.5
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt  # This job also runs in the test stage.
  stage: django
  allow_failure: true    # It can run at the same time as unit-test-job (in parallel).
  script:
  # - find . -type f -name '*.py' ! -path '*/migrations/*' -exec autopep8 --in-place --aggressive --aggressive '{}' \;
  - cd neuro_arcade
  - ruff lint

react-creation:
  stage: reactCreation
  image: node:latest
  before_script:
    - cd neuro_arcade
    - cd reactapp
    - npm install --force
  script:
    echo "React compiled"




unit-test-r-job:
  stage: react
  image: node:latest
  before_script:
    - cd neuro_arcade
    - cd reactapp
    - npm install --force
  script:
      #Temporary until we have tests as it will fail if there are no tests
    - npm test --passWithNoTests
#    - npm test--coverage --passWithNoTests
  
lint-test-r-job:
  stage: react
  allow_failure: true 
  image: node:latest
  before_script:
    - cd neuro_arcade
    - cd reactapp
    - npm install --force
  script:
    - eslint  --fix src/**/*.js
    




