stages:          # List of stages for jobs, and their order of execution
  - test

variables:
  PYTHON_VERSION: "3.11.5"
  MYSQL_DATABASE: $MYSQL_DB
  MYSQL_ROOT_PASSWORD: $MYSQL_PASS
  MYSQL_USER: $MYSQL_USER
  MYSQL_PASSWORD: $MYSQL_PASS

.react-job:
  cache:
    key: npm
    policy: pull-push
    paths:
      - neuro_arcade/reactapp/.npm/
  before_script:
    - cd neuro_arcade
    - cd reactapp
    - npm ci --cache .npm --prefer-offline

.django-job:
  image: python:latest
  before_script:
    - pip install -r requirements.txt

django-migrate-test-job:
  extends: .django-job
  stage: test
  script:
    - python neuro_arcade/manage.py makemigrations --check
    - python neuro_arcade/manage.py migrate
    - python neuro_arcade/manage.py check

django-unit-test-job: 
  extends: .django-job
  stage: test
  script:
    - cd neuro_arcade
    - python manage.py test

react-unit-test-job:
  extends: .react-job
  stage: test
  image: node:latest
  script:
    - export CI=1
    - npm test
    #  Maybe try and export as artifact at some point?
    - npm test -- --coverage
